export const network = "{{network}}";
export const uniswapFactoryAddress = "{{uniswapFactory}}";
export const wethAddress = "{{weth}}";
export const usdAddress = "{{usd}}";

// Deprecated
export const btcGateway = "{{btcGateway}}";
export const zecGateway = "{{zecGateway}}";
export const bchGateway = "{{bchGateway}}";
export const btc = "{{btc}}";
export const zec = "{{zec}}";
export const bch = "{{bch}}";
